# Generated by Django 2.1.3 on 2019-08-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=255)),
                ('Organizer', models.CharField(max_length=255)),
                ('Start', models.DateTimeField()),
                ('Attendees', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
