# Generated by Django 2.1.3 on 2019-08-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Eventid', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'attendees',
            },
        ),
    ]
